---
output:
  pdf_document:
header-includes:
- \usepackage{caption}
- \captionsetup[figure]{labelformat=empty}
- \captionsetup[table]{labelformat=empty}
---

```{r Load libraries, echo=FALSE, message=FALSE, cache=FALSE, warning=FALSE}
library(dplyr) #For handling fata 
library(sf) #For handling coordinates and plotting
library(scales) #For plotting (decimals on axes)
library(lubridate) #To operate with dates
library(tidyr) #Reshape data (wide format)
library(stringr) #Fix/modify strings
library(forcats)
library(readr)
#Load libraries for plotting
library(giscoR) #Maps
library(ggstar) #cool shapes as points
library(ggplot2) #general plotting
library(ggtree) #phylo trees
library(ggpattern) #cool shapes in barplots
library(patchwork) #plot organisation
library(cowplot) #plot organisation
library(viridis) #colours
library(ggnewscale)
library(ggtreeExtra)
library(kableExtra)

```


```{r echo=FALSE, message=FALSE, cache=FALSE, warning=FALSE, out.width="95%", fig.cap= "\\textbf{Figure 2}. Graphs (a-b-c) indicate the accumulation curves for pollinators, plants, and their interactions across sampling sites. Grey solid lines represent 100 randomized accumulation curves, the black solid lines represents the interpolated curve (i.e., the mean across curves), and the red dashed lines illustrates the extrapolated curve for approximately 3000 sampling sites. The solid black points indicate the number of species and interactions contained in the database. Graph (d) shows the accumulation curve of pollinator species across increasing number of plant species. This last graph uses the same color and shape structure as the ones in the top panel. Graphs (e-f) indicate the percentage of occurrence (i.e., incidence) of plant and pollinator species across sampling sites. Species on the left (i.e., common) are found in many sampling sites, while species on the right (i.e., rare) are found in few or only a single sampling site.", fig.width=10, fig.height=6, out.width="115%"}

#Pollinators-----
poll_output = readRDS("../Data/Working_files/pollinator_sampling_coverage.rds")
pollinators_curves = readRDS("../Data/Working_files/collectors_curves_pollinators.rds")
#Create dataset
d_poll = poll_output$iNextEst$Network_id
#Check cols
d_poll$col = d_poll$method

#Now create tibble with same structure
a_poll = tibble(t = pollinators_curves$Study_sampled, 
           method = as.character(pollinators_curves$iteration), 
           qD = pollinators_curves$Unique_spp_cumulative,
           col = "collectors")

#Bind datasets 
d_poll1 = bind_rows(d_poll, a_poll)
d_poll1_point = d_poll1 %>%  filter(method == "observed")
d_poll1_lines = d_poll1 %>%  filter(!method == "observed")

#Order levels
d_poll1_lines$col = factor(d_poll1_lines$col, levels = c("collectors", "interpolated", "extrapolated"))
#Plot
p1 = ggplot(d_poll1_lines, aes(x = t, y = qD, group = method, color = col)) +
geom_line(aes(linetype = col),size = 0.65) +
scale_colour_manual(values = c("gray", "black", "red"), labels = c("Randomizations", "Interpolated", "Extrapolated")) +
scale_linetype_manual(values = c("solid", "solid", "dashed"),  labels = c("Randomizations", "Interpolated", "Extrapolated")) + 
geom_ribbon(aes(ymin = qD.LCL, 
    ymax=qD.UCL, fill = col),alpha=0.2, colour = NA, show.legend = FALSE)+
scale_fill_manual(values = c("gray", "black", "red")) +
geom_point(data = d_poll1_point, col = "black", size=2) + 
ylab("Pollinator species") +
xlab("Sampling sites") +
theme_bw() +
coord_cartesian(expand = FALSE, clip = "off")  +
xlim(0,3000)+
ylim(0, 3000) +
ggtitle("(a)") +
theme(plot.margin = margin(r = 12)) 

#Plants-----
plant_output = readRDS("../Data/Working_files/plant_sampling_coverage.rds")
plant_curves = readRDS("../Data/Working_files/collectors_curves_plants.rds")
#Create dataset
d_plant = plant_output$iNextEst$Network_id
#Check cols
d_plant$col = d_plant$method

#Now create tibble with same structure
a_plant = tibble(t = plant_curves$Study_sampled, 
           method = as.character(plant_curves$iteration), 
           qD = plant_curves$Unique_spp_cumulative,
           col = "collectors")

#Bind datasets 
d_plant1 = bind_rows(d_plant, a_plant)
d_plant1_point = d_plant1 %>%  filter(method == "observed")
d_plant1_lines = d_plant1 %>%  filter(!method == "observed")

#Order levels
d_plant1_lines$col = factor(d_plant1_lines$col, levels = c("collectors", "interpolated", "extrapolated"))
#Plot
p2 = ggplot(d_plant1_lines, aes(x = t, y = qD, group = method, color = col)) +
geom_line(aes(linetype = col), size = 0.65) +
scale_colour_manual(values = c("gray", "black", "red"), labels = c("Randomizations", "Interpolated", "Extrapolated")) +
scale_linetype_manual(values = c("solid", "solid", "dashed"),  labels = c("Randomizations", "Interpolated", "Extrapolated")) + 
geom_ribbon(aes(ymin = qD.LCL, 
    ymax=qD.UCL, fill = col),alpha=0.2, colour = NA, show.legend = FALSE)+
scale_fill_manual(values = c("gray", "black", "red")) +
geom_point(data = d_plant1_point, col = "black", size=2) + 
ylab("Plant species") +
xlab("Sampling sites") +
theme_bw() +
coord_cartesian(expand = FALSE, clip = "off")  +
xlim(0,3000)+
ylim(0, 3000)+
ggtitle("(b)")+
theme(plot.margin = margin(r = 12)) 



#Interactions-----
int_output = readRDS("../Data/Working_files/interactions_sampling_coverage.rds")
interactions_curves = readRDS("../Data/Working_files/collectors_curves_interactions.rds")
#Create dataset
d_int = int_output$iNextEst$Network_id
#Check cols
d_int$col = d_int$method

#Now create tibble with same structure
a_poll = tibble(t = interactions_curves$Study_sampled, 
           method = as.character(interactions_curves$iteration), 
           qD = interactions_curves$Unique_spp_cumulative,
           col = "collectors")

#Bind datasets 
d_int1 = bind_rows(d_int, a_poll)
d_int1_point = d_int1 %>%  filter(method == "observed")
d_int1_lines = d_int1 %>%  filter(!method == "observed")

#Plot
#Order levels
d_int1_lines$col = factor(d_int1_lines$col, levels = c("collectors", "interpolated", "extrapolated"))
#Plot
p3 = ggplot(d_int1_lines, aes(x = t, y = qD, group = method, color = col)) +
geom_line(aes(linetype = col), size = 0.65) +
scale_colour_manual(values = c("gray", "black", "red"), labels = c("Randomizations", "Interpolated", "Extrapolated")) +
scale_linetype_manual(values = c("solid", "solid", "dashed"),  labels = c("Randomizations", "Interpolated", "Extrapolated")) + 
geom_ribbon(aes(ymin = qD.LCL, 
    ymax=qD.UCL, fill = col),alpha=0.2, colour = NA, show.legend = FALSE)+
scale_fill_manual(values = c("gray", "black", "red")) +
geom_point(data = d_int1_point, col = "black", size=2) + 
ylab("Interactions") +
xlab("Sampling sites") +
theme_bw() +
coord_cartesian(expand = FALSE, clip = "off")  +
xlim(0,3000) +
ylim(0, 30000)+
ggtitle("(c)")

#----------------#
#Pollinators
#----------------#
#Read data
data = readRDS("../Data/Working_files/Interactions_uncounted.rds")%>% 
mutate(Network_id = paste0(Study_id, Network_id))  
#First select cols of rank, accepted name and study ID
#Then select unique levels by study ID
#Now sum levels (maximum can be as maximum number of studies)
poll_spread = data %>% 
select(Pollinator_rank, Pollinator_accepted_name, Network_id) %>% 
group_by(Network_id) %>% 
filter(Pollinator_rank == "SPECIES") %>% 
distinct(Pollinator_accepted_name) %>% 
ungroup() %>% 
count(Pollinator_accepted_name) %>% 
rename(n_networks_shared = n) %>% 
arrange(-n_networks_shared) %>% 
mutate(Percent_total = n_networks_shared / n_distinct(data$Network_id))
  
#Seelect quantile 50% from the total number of species
spp_number = poll_spread %>%  
select(Pollinator_accepted_name) %>% 
n_distinct()
df = seq(1, spp_number)
quantile_50 = quantile(df, 0.5)

#Obtain most common pollinator for plotting
most_common_poll = poll_spread %>% filter(n_networks_shared == max(n_networks_shared)) %>%
select(Pollinator_accepted_name) %>% pull() 

#Plot
o1 = ggplot(poll_spread, 
aes(reorder(Pollinator_accepted_name,-Percent_total), Percent_total)) +
geom_bar(stat = "identity", 
           color = "#D55E00",
           lwd = 0.03, fill = "#D55E00") +
ylab("Shared pollinators (%)") +
theme_minimal()+
theme(axis.text.x = element_blank(),
  axis.ticks.x=element_blank(),
  axis.ticks.y = element_line(size = 0.2),
  panel.grid.major.x = element_blank(),
  panel.grid.minor.y = element_blank(),
  panel.grid.major.y = element_line(size=0.2, linetype = 2)) +
xlab("Pollinator species") +
ylab("Occurrence across sampling sites") + 
geom_vline(xintercept = quantile_50, linetype="dashed", 
color = "black", size=0.35) + 
annotate(geom="text", x=1450, y=0.60, label="50th percentile",color="black", size = 3) +
annotate(geom="text", x=140, y=0.67, label=most_common_poll[1],color="black",  fontface = 'italic', size = 3)+
annotate(geom="text", x=200, y=-0.05, label="Common spp."
      ,color="black",  size = 3) +
annotate(geom="text", x=1800, y=-0.05, label="\'Rare\' spp."
      ,color="black",  size = 3)  +
scale_y_continuous(breaks = seq(0, 0.7, by= 0.25), expand = c(0, 0)) + 
coord_cartesian(xlim=c(0, nlevels(factor(poll_spread$Pollinator_accepted_name))),
                ylim=c(0,0.7), clip="off") +
ggtitle("(e)")

#----------------#
#Plants
#----------------#
plant_spread = data %>% 
select(Plant_rank, Network_id, Plant_accepted_name) %>% 
group_by(Network_id) %>% 
filter(Plant_rank == "SPECIES") %>% 
distinct(Plant_accepted_name) %>% 
ungroup() %>% 
count(Plant_accepted_name) %>% 
rename(n_networks_shared = n) %>% 
arrange(-n_networks_shared) %>% 
mutate(Percent_total = n_networks_shared / n_distinct(data$Network_id))
  
#Seelect quantile 50% from the total number of species
spp_number = plant_spread %>%  
select(Plant_accepted_name) %>% 
n_distinct()
df = seq(1, spp_number)
quantile_50 = quantile(df, 0.5)

#Obtain most common plant for plotting
most_common_plant = plant_spread %>% filter(n_networks_shared == max(n_networks_shared)) %>%
select(Plant_accepted_name) %>% pull() 

o2 = ggplot(plant_spread, 
aes(reorder(Plant_accepted_name,-Percent_total), Percent_total, fill = Plant_accepted_name)) +
geom_bar(stat = "identity", 
           color = "#009E73",
           lwd = 0.03, fill = "#009E73") +
theme_minimal()+
theme(axis.text.x = element_blank(),
         axis.ticks.x=element_blank(),
         axis.ticks.y = element_line(size = 0.2),
         panel.grid.major.x = element_blank(),
         panel.grid.minor.y = element_blank(),
         panel.grid.major.y = element_line(size=0.2, linetype =  2)) +
xlab("Plant species") +
ylab("Occurrence across sampling sites") + 
geom_vline(xintercept = quantile_50, linetype="dashed", 
          color = "black", size=0.35) + 
annotate(geom="text", x=950, y=0.60, label="50th percentile",color="black", size = 3) + 
annotate(geom="text", x=100, y=0.4, label=most_common_plant[1]
      ,color="black",  fontface = 'italic', size = 3)+
annotate(geom="text", x=150, y=-0.05, label="Common spp."
      ,color="black",  size = 3) +
annotate(geom="text", x=1200, y=-0.05, label="\'Rare\' spp."
      ,color="black",  size = 3) + 
scale_y_continuous(breaks = seq(0, 0.7, by= 0.25), expand = c(0, 0), labels = label_number(accuracy = 0.01)) +
coord_cartesian(xlim=c(0, nlevels(factor(plant_spread$Plant_accepted_name))),
                ylim=c(0, 0.7), clip="off") +
ggtitle("(f)")

#Pollinator by plant species
plant_poll_curves = readRDS("../Data/Working_files/collectors_curves_plant_ploll.rds")
plant_poll_output = readRDS("../Data/Working_files/plant_poll_spp_sampling_coverage.rds")

#Create dataset
d_pp = plant_poll_output$iNextEst$Plant_id
#Check cols
d_pp$col = d_pp$method

#Now create tibble with same structure
a_poll = tibble(t = plant_poll_curves$Plant_sampled, 
           method = as.character(plant_poll_curves$iteration), 
           qD = plant_poll_curves$Unique_spp_cumulative,
           col = "collectors")

#Bind datasets 
d_pp1 = bind_rows(d_pp, a_poll)
d_pp1_point = d_pp1 %>%  filter(method == "observed")
d_pp1_lines = d_pp1 %>%  filter(!method == "observed")

#Plot
#Order levels
d_pp1_lines$col = factor(d_pp1_lines$col, levels = c("collectors", "interpolated", "extrapolated"))
#Plot
pp1 = ggplot(d_pp1_lines, aes(x = t, y = qD, group = method, color = col)) +
geom_line(aes(linetype = col)) +
scale_colour_manual(values = c("gray", "black", "red"), labels = c("Randomizations", "Interpolated", "Extrapolated")) +
scale_linetype_manual(values = c("solid", "solid", "dashed"),  labels = c("Randomizations", "Interpolated", "Extrapolated")) + 
geom_ribbon(aes(ymin = qD.LCL, 
    ymax=qD.UCL, fill = col),alpha=0.2, colour = NA, show.legend = FALSE)+
scale_fill_manual(values = c("gray", "black", "red")) +
geom_point(data = d_pp1_point, col = "black") + 
ylab("Pollinator species") +
xlab("Plant species") +
theme_bw() +
coord_cartesian(expand = FALSE, clip = "off") +
ggtitle("(d)") +
scale_x_continuous(breaks = seq(0, 2800, by = 1000), limits=c(0,2800)) +
scale_y_continuous(breaks = seq(0, 2600, by = 1000), limits=c(0,2600)) +
theme(legend.position = "none")

#Plot all
p1 + p2 + p3 + pp1 + o1 + o2 + plot_layout(guides = "collect", nrow = 2, ncol=3) & theme(legend.title=element_blank(),
      axis.title = element_text(size=12, face = "bold"),
      axis.text = element_text(size=10),
      plot.title = element_text(size=18))

#a/b


```
