---
format:
  pdf:
    include-in-header: 
      text: |
        \usepackage{lscape}
        \newcommand{\blandscape}{\begin{landscape}}
        \newcommand{\elandscape}{\end{landscape}}
        \usepackage{caption}
        \captionsetup[figure]{labelformat=empty}
        \captionsetup[table]{labelformat=empty}
        \usepackage{lineno}
        \linenumbers
bibliography: references.bib
csl: apa_7th.csl
latex-tinytex: false
link-citations: TRUE
linkcolor: RoyalBlue
urlcolor: RoyalBlue
---

```{r Load libraries, echo=FALSE, message=FALSE, cache=FALSE, warning=FALSE}

library(readr)
library(dplyr)

#Read author list 
authors = readr::read_csv("../Data/Manuscript_info/Authorship_ordered.csv")
#Print authors
authors = authors %>% 
summarise(col = paste(Coauthor_name_aff, collapse="| ")) %>% 
pull()
#Read affiliation list 
aff_list = readr::read_csv("../Data/Manuscript_info/Affiliation_list.csv")
aff_list = aff_list %>% 
summarise(col = paste0(Aff_number_Aff, "\\",sep="")) %>% 
pull()


```

\vspace*{-14mm}

**Title**: 

EuPPollNet: A European database of plant-pollinator networks

**Authors**:

`r authors`

**Corresponding author** = barragansljose@gmail.com\
*All authors excluding the first four and last are ordered alphabetically*


**Affiliations**:

\begingroup
\small

`r aff_list`

\small
\endgroup

**Acknowledgements**:

We thank all the taxonomists and ecologists that has made this database possible by contributing with their fieldwork data. 

**Biosketch**: 

Dr. Jose B. Lanuza is a long term collaborator of Dr. Ignasi Bartomeus. Their work focuses on understanding the ecological processes that drive plant-pollinator interactions at different ecological scales. This research is another piece of the puzzle that will contribute to our understanding of how interactions change with various environmental drivers. Our work has primarily involved flowering plants and pollinators, where we have addressed questions related to their coexistence, interaction probability, and ecology. We have created the first database of Iberian bees for Spain and are strong advocates for reproducible science; this work is a perfect example of it. Further examples of the ongoing work and past projects can be consulted at Ignasi Bartomeus lab web page: <https://bartomeuslab.com/projects/>.



