---
title: "Protocols"
author: "Bartomeus, Molina, ..."
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Core observations

Aim: Understand the network of interactions between plants and pollinators and 
consequences for plant reproduction.    

Data collection is done in 12 to 16 independent sites in a gradient of land use intensity across the Guadalquivir valley. All sites are sampled every ~ 15 days (weather permitting) for a total of 6 to 8 rounds per year. All sites are situated in open pine woodlands with an understory dominated by Lavender, Rosemary and Cistaceas. Data collection covers the whole  season from early spring (February) to Summer (June). We only sample on good weather conditions (no rain, extreme cold or high wind speeds).

Monitoring protocols:

1)	**Transect walks**:A fixed 100 meters straight line within each plot is walked at a slow pace in 30 minutes. During that time,  we record all the interactions that are observed between pollinators and flowering plants. In the case that we do not know the pollinator, it is captured with a hand net and stored in a plastic jar, which will be numbered and noted in a central notebook. Time devoted to capturing insects is deducted from the total sampling time. Since 2020 we repeat this transect twice to estimate detectability. In 2021 we ran this protocol weekly (12 sampling rounds). 

After the 30 minutes transect walk, we conduct a __flower count__ along the same 100 meter transect. Every 10 meters we count all the species of flowering plants in about 1 meter around us (~3 m2). Overall, we do 10 counts along the transect.

-	**Focal census**: In addition, we perform focal census on specific plants. Those consist of choosing a flowering plant and observing all visitors during a 3 minute census, except the years 2015 and 2016, where we observed all visitors during 5 minutes. In the case that we do not know the pollinator species, it is captured with a hand net and stored in a plastic jar, which will be numbered and noted in a central notebook. Time devoted to capturing insects is deducted from the total sampling time. Usually, the most common plant species are selected in each site.

- **Fruit and seed set**: 13 plots were sampled between 2015 and 2019 and the fruit set and seed set were obtained for 13 different plant species (3-4 individuals per plant species). For each individual plant, the number of developed fruits (fruit yes), not developed fruits (fruits no), predated fruit, and dispersed fruit were recorded. In 2015 and 2016 fruits were counted per branch, whereas 2017, 2018 and 2019 fruits were aggregated for the whole plant. The fruit formed was obtained as the sum of fruit yes + predated fruit +  dispersed fruit, and the total potential fruits as the sum of the fruit formed + fruit no. The fruit proportion was calculated as formed fruit divided by total fruit for each individual per plant species at each site and year.

For the seed set, the number of seeds per fruit was counted (at least 3 fruit per individual) and each seed was weighed. In some fruits, more than one seed was weighed (for example, for individual A1, fruit "a" has 2 seeds and both are weighed), so the average weight of the seed was calculated per fruit in each individual. The average number of seeds per fruit and the average weight of the seed per fruit were obtained using the total amount of fruits per individual per plant species.

-	**Outside transect**: We also opportunistically capture rare pollinators outside of our transect, so that we can collect more complete information about the pollinators that we have in the plots at that time. Captured pollinators are placed in labeled jars for later identification in the lab and registered in the notebook.

-	**Identification process**: Due to the amount of bees captured we conserved them in a cooler at -20ºC. At the lab, the bees are pinned and labeled. Later, we identify them using the scarce taxonomic information available through determination keys. All the specimens were sent to a taxonomic expert to check the identification done and to identify the remaining unidentified species. The labels always contains the following information: Site, date, jar number, plant, family or genus if we know.

- **single visit deposition**: TBA

Departures from common protocols and important changes.

- Since 2020 we conduct each transect twice.
- For 2022, we have extra data of butterfly transects and 18 new sites (Nerea).
- We have extra data on transects from David Paz for 2015 year.
- We have extra data on cavity nesting bees for XXXX year.
- We have extra data on butterflies transects from XXXX year (Mark de Jong)
- Pairing between focal plants observed and fruit set?


